{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- $argoDestNamespace := (printf "%s-%s" $.Values.global.pattern .name) -}}
{{- if $.Values.global.singleArgoCD }}
{{- $argoDestNamespace = $.Values.global.vpArgoNamespace -}}
{{- end }}
{{- if ($.Values.global.deletePattern | eq "DeleteSpoke" ) }}
{{- else }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.global.pattern }}-{{ .name }}-notwrapped
  namespace: {{ $.Values.global.vpArgoNamespace }}
  annotations:
    notice.argocd.argoproj.io/severity: info
    notice.argocd.argoproj.io/content: "App of Apps"
  labels:
    validatedpatterns.io/pattern: {{ $.Values.global.pattern }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  {{- if $.Values.global.multiSourceSupport }}
  sources:
    - repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
      targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
      ref: patternref
      {{/* If we're using the clustergroup chart from a git repo let's use those */}}
      {{- $clusterGroupGitRepoUrl := "" }}
      {{- if and $.Values.main $.Values.main.multiSourceConfig }}
        {{- $clusterGroupGitRepoUrl = $.Values.main.multiSourceConfig.clusterGroupGitRepoUrl }}
      {{- end }}
      {{- $clusterGroupChartGitRevision := "" }}
      {{- if and $.Values.main $.Values.main.multiSourceConfig }}
        {{- $clusterGroupChartGitRevision = $.Values.main.multiSourceConfig.clusterGroupChartGitRevision }}
      {{- end }}
    - repoURL: {{ coalesce $clusterGroupGitRepoUrl $.Values.global.multiSourceRepoUrl }}
      targetRevision: {{ coalesce $clusterGroupChartGitRevision $.Values.global.multiSourceTargetRevision }}
      {{- if and $.Values.main $.Values.main.multiSourceConfig (hasKey $.Values.main.multiSourceConfig "clusterGroupGitRepoUrl") }}
      path: "."
      {{- else }}
      chart: clustergroup
      {{- end }}
      helm:
        ignoreMissingValueFiles: true
        values: |
          extraParametersNested:
          {{- range $k, $v := $.Values.extraParametersNested }}
            {{ $k }}: {{ printf "%s" $v | quote }}
          {{- end }}
        valueFiles:
        {{- include "acm.app.policies.multisourcevaluefiles" . | nindent 8 }}
        {{- range $valueFile := .extraValueFiles }}
        - {{ $valueFile | quote }}
        {{- end }}
        parameters:
        {{- include "acm.app.policies.helmparameters" $ | nindent 8 }}
        - name: clusterGroup.name
          value: {{ $group.name }}
        {{- range $k, $v := $.Values.extraParametersNested }}
        - name: {{ $k }}
          value: {{ printf "%s" $v | quote }}
        {{- end }}
       {{- range .helmOverrides }}
        - name: {{ .name }}
          value: {{ .value | quote }}
       {{- end }}
       {{- if .fileParameters }}
        fileParameters:
        {{- range .fileParameters }}
        - name: {{ .name }}
          path: {{ .path }}
        {{- end }}
       {{- end }}
  {{- else }}
  source:
    repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
    targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
    path: {{ default "common/clustergroup" .path }}
    helm:
      ignoreMissingValueFiles: true
      values: |
        extraParametersNested:
        {{- range $k, $v := $.Values.extraParametersNested }}
          {{ $k }}: {{ printf "%s" $v | quote }}
        {{- end }}
      valueFiles:
      {{- include "acm.app.policies.valuefiles" . | nindent 6 }}
      {{- range $valueFile := .extraValueFiles }}
      - {{ $valueFile | quote }}
      {{- end }}
      parameters:
      {{- include "acm.app.policies.helmparameters" $ | nindent 6 }}
      - name: clusterGroup.name
        value: {{ $group.name }}
      {{- range $k, $v := $.Values.extraParametersNested }}
      - name: {{ $k }}
        value: {{ printf "%s" $v | quote }}
      {{- end }}
     {{- range .helmOverrides }}
      - name: {{ .name }}
        value: {{ .value | quote }}
     {{- end }}
     {{- if .fileParameters }}
      fileParameters:
      {{- range .fileParameters }}
      - name: {{ .name }}
        path: {{ .path }}
      {{- end }}
     {{- end }}
  {{- end }}{{/* if $.Values.global.multiSourceSupport */}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $argoDestNamespace }}
  info:
    - name: "VP"
      value: "https://validatedpatterns.io APP OF APPS"
  syncPolicy:
    automated:
    {{- if ($.Values.global.deletePattern | ne "none" ) }}
      prune: true
    {{- else }}
      prune: false
    {{- end }}
      selfHeal: true
    retry:
      limit: {{ default 20 $.Values.global.options.applicationRetryLimit }}
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
{{- end }}
{{- end }}
